FROM public.ecr.aws/docker/library/alpine:3.19
RUN apk add --no-cache socat iproute2
# DNS resolver configuration is set at runtime in the entrypoint script
COPY dstack-util /app/dstack-util
RUN chmod +x /app/dstack-util
COPY enclave_run_get_keys.sh /app/run.sh
RUN chmod +x /app/run.sh
ENTRYPOINT ["/app/run.sh"]
